/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import DAO.DichVu_dao;
import Enitity.DichVu;

/**
 *
 * @author Lenovo
 */
public class CapNhatDichVu extends javax.swing.JFrame {

    /**
     * Creates new form capnhatdichvu
     */

    public CapNhatDichVu() {
        initComponents();
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_MaDV = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_TenDV = new javax.swing.JTextField();
        btn_Tim = new javax.swing.JButton();
        btn_LamMoi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_dichvu = new javax.swing.JTable();
        btn_Them = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txt_SoLuong = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_dichvu1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txt_tenphong = new javax.swing.JTextField();
        txt_tongtiendichvu = new javax.swing.JTextField();
        btn_Bot = new javax.swing.JButton();
        btn_Xoa = new javax.swing.JButton();
        btn_QuayLai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        txt_SoLuong.setPreferredSize(new java.awt.Dimension(50, 28));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CẬP NHẬT DỊCH VỤ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addGap(336, 336, 336))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tất cả dịch vụ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Mã : ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Tên: ");

        btn_Tim.setText("Tìm");
        btn_Tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimActionPerformed(evt);
            }
        });

        btn_LamMoi.setText("Làm mới");
        btn_LamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LamMoiActionPerformed(evt);
            }
        });

        table_dichvu.setBackground(new java.awt.Color(199, 199, 231));
        String[] headers = "Mã DV;Tên dịch vụ;Số lượng;Giá".split(";");
        tableModel = new DefaultTableModel(headers, 0);
        table_dichvu.setAutoCreateRowSorter(true);
        jScrollPane1.setViewportView(table_dichvu = new JTable(tableModel));

        btn_Them.setText("Thêm");
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Số lượng :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Tim, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_MaDV, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btn_LamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_TenDV, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(208, 208, 208))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_MaDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txt_TenDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txt_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Tim)
                    .addComponent(btn_LamMoi)
                    .addComponent(btn_Them))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                .addGap(61, 61, 61))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Dịch vụ đã thêm");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Tên phòng :  ");

        table_dichvu1.setBackground(new java.awt.Color(199, 199, 231));
        String[] headers2 = "Mã DV;Tên dịch vụ;Số lượng;Giá".split(";");
        tableModel1 = new DefaultTableModel(headers2, 0);
        table_dichvu1.setAutoCreateRowSorter(true);
        jScrollPane2.setViewportView(table_dichvu1 = new JTable(tableModel1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Tổng tiền dịch vụ: ");

        txt_tenphong.setBackground(new java.awt.Color(204, 204, 255));
        txt_tenphong.setText("..................................................................");
        txt_tenphong.setBorder(null);

        txt_tongtiendichvu.setBackground(new java.awt.Color(204, 204, 255));
        txt_tongtiendichvu.setText("...............................................VND");
        txt_tongtiendichvu.setBorder(null);
        txt_tongtiendichvu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tongtiendichvuActionPerformed(evt);
            }
        });

        btn_Bot.setText("Bớt ");
        btn_Bot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BotActionPerformed(evt);
            }
        });

        btn_Xoa.setText("Xóa");
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txt_tongtiendichvu, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_tenphong, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(btn_Bot, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_tenphong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Xoa)
                    .addComponent(btn_Bot))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_tongtiendichvu, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        btn_QuayLai.setText("Quay lại");
        btn_QuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QuayLaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_QuayLai)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_QuayLai)
                .addGap(10, 10, 10))
        );

        pack();
        fillDataIntoTable();
        fillDataIntoTable1();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_tongtiendichvuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tongtiendichvuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tongtiendichvuActionPerformed

    private void btn_TimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimActionPerformed
        Tim();
    }//GEN-LAST:event_btn_TimActionPerformed

    private void btn_LamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LamMoiActionPerformed
       fillDataIntoTable();
       fillDataIntoTable1();
       txt_MaDV.setText("");
       txt_TenDV.setText(""); 
       txt_SoLuong.setText("");
       txt_tenphong.setText(maPhong);
       txt_tongtiendichvu.setText(tongtien+"");
    }//GEN-LAST:event_btn_LamMoiActionPerformed

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        Them();
        fillDataIntoTable();
        fillDataIntoTable1();
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void btn_BotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BotActionPerformed
        Bot();
        fillDataIntoTable();
        fillDataIntoTable1();
    }//GEN-LAST:event_btn_BotActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
       Xoa();
       fillDataIntoTable();
       fillDataIntoTable1();
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void btn_QuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QuayLaiActionPerformed
    	this.dispose();
    }//GEN-LAST:event_btn_QuayLaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CapNhatDichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CapNhatDichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CapNhatDichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CapNhatDichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CapNhatDichVu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Bot;
    private javax.swing.JButton btn_LamMoi;
    private javax.swing.JButton btn_QuayLai;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_Tim;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table_dichvu;
    private javax.swing.JTable table_dichvu1;
    private javax.swing.JTextField txt_MaDV;
    private javax.swing.JTextField txt_SoLuong;
    private javax.swing.JTextField txt_TenDV;
    private javax.swing.JTextField txt_tenphong;
    private javax.swing.JTextField txt_tongtiendichvu;
    // End of variables declaration//GEN-END:variables
    private DefaultTableModel tableModel;
    private DefaultTableModel tableModel1;
    private ArrayList<DichVu> dsDichVu = new ArrayList<>();
    private ArrayList<DichVu> dsDichVu1 = new ArrayList<>();
    private DichVu_dao dao= new DichVu_dao();
    private String maPhong;
    private double tongtien ;
    
    public String getId() {
    	return maPhong;
    }
    
    public void setId(String maPhong) {
    	this.maPhong =maPhong;
    }
    
    private void fillDataIntoTable() {

    	dsDichVu.clear();
    	if (tableModel.getRowCount() > 0) {
			for (int i = tableModel.getRowCount() - 1; i > -1; i--) {
				tableModel.removeRow(i);
			}
		}
    	dsDichVu = dao.getAll();
    	for(DichVu dv: dsDichVu) {
			String[] rowData = { dv.getMaDichVu(), dv.getTenDichVu(),dv.getSoLuong()+"",dv.getGia()+""	};
			tableModel.addRow(rowData);

    	}
    	table_dichvu.setModel(tableModel);
    }
    private void fillDataIntoTable1() {
    	tongtien =0;

    	dsDichVu1.clear();
    	if (tableModel1.getRowCount() > 0) {
			for (int i = tableModel1.getRowCount() - 1; i > -1; i--) {
				tableModel1.removeRow(i);
			}
		}
    	dsDichVu1 = dao.getChiTietDichVu(maPhong);
    	for(DichVu dv1: dsDichVu1) {
    		
    		 double gia=dv1.getGia()*dv1.getSoLuong();
    		 tongtien += gia;
			String[] rowData = { dv1.getMaDichVu(), dv1.getTenDichVu(),dv1.getSoLuong()+"",gia+""	};
			tableModel1.addRow(rowData);

    	}
    	table_dichvu1.setModel(tableModel1);
    	txt_tongtiendichvu.setText(tongtien+" VND");
    }

    
    private void Them() {
    	
    	int soLuongThuc=0;
    	int select = table_dichvu.getSelectedRow();
    	if(select == -1) {
        	JOptionPane.showMessageDialog(this, "Vui lòng chọn dịch vụ !");
        }
    	else if(Integer.parseInt(txt_SoLuong.getText())<0) {JOptionPane.showMessageDialog(this,"Số lượng không được âm !!!");}
    	else if (txt_SoLuong.getText()=="") {JOptionPane.showMessageDialog(this,"Chưa nhập số lượng !!!");}
    	else {
        	DichVu dv =dsDichVu.get(select);
        	dsDichVu1 = dao.getChiTietDichVu(maPhong);
        	
            if (dsDichVu1.isEmpty()) 
            {            	
            	    dsDichVu1.add(dv);            	
            		int soluong= Integer.parseInt(txt_SoLuong.getText()) ;
            		dao.ThemChiTietDichVu(dv, maPhong, soluong);
            		dao.UpdateDichVuSauKhiThemBot(dv, dv.getSoLuong()-Integer.parseInt(txt_SoLuong.getText()));
            	          	
            }
            else {
            	
            	int f=0;
            	int soluongsanpham=0;
            	for(DichVu dv1: dsDichVu1 ) {
            		if(dv1.getMaDichVu().equals(dv.getMaDichVu())) {
            			if(dv.getSoLuong()>=Integer.parseInt(txt_SoLuong.getText())) {
                			soluongsanpham =dv1.getSoLuong()+Integer.parseInt(txt_SoLuong.getText());         			
                		    dao.UpdateThemChiTietDichVu(dv1, maPhong, soluongsanpham);
                		    dao.UpdateDichVuSauKhiThemBot(dv, dv.getSoLuong()-Integer.parseInt(txt_SoLuong.getText()));
                		    f=1;
                			break;
            			}
            			else if(dv.getSoLuong()<Integer.parseInt(txt_SoLuong.getText())) {
            				JOptionPane.showMessageDialog(this,"Số lượng quá lớn !!!");
            			}
 
            	}
            		//
            	          		          		
            	
 //           	
            }
            	if(f==0) {
            		if(dv.getSoLuong()<Integer.parseInt(txt_SoLuong.getText())) {
        				JOptionPane.showMessageDialog(this,"Số lượng quá lớn !!!");
        			}
        			//(dv.getSoLuong()>=Integer.parseInt(txt_SoLuong.getText())) 
            		else {
            			dsDichVu1.add(dv);            	
                		int soluong= Integer.parseInt(txt_SoLuong.getText()) ;
                		dao.ThemChiTietDichVu(dv, maPhong, soluong);
                   		dao.UpdateDichVuSauKhiThemBot(dv, dv.getSoLuong()-Integer.parseInt(txt_SoLuong.getText()));
            		}
        			
        		} 
        	
        	}
    	}
        	
          	
    }
    
    public void Bot() {
    	int soluongbot = Integer.parseInt(txt_SoLuong.getText());
    	int select = table_dichvu1.getSelectedRow();
    	
    	if(select == -1) {
        	JOptionPane.showMessageDialog(this, "Vui lòng chọn dịch vụ !");
        }
    	else if(Integer.parseInt(txt_SoLuong.getText())<0) {JOptionPane.showMessageDialog(this,"Số lượng không được âm !!!");}
    	else if (txt_SoLuong.getText()=="") {JOptionPane.showMessageDialog(this,"Chưa nhập số lượng !!!");}
        else {
        	DichVu dv1 =dsDichVu1.get(select);
        	dsDichVu = dao.getAll();
        	int soluong = dv1.getSoLuong()-soluongbot;
         if(soluong<0) {JOptionPane.showMessageDialog(this,"Số lượng bớt quá lớn !!!");}
        	
         else {
        	 int f=0;
        	 for(DichVu dv : dsDichVu) {
        		 if(dv.getMaDichVu().equals(dv1.getMaDichVu())) {
        			 if(soluong==0) {
        	        		dao.deleteChiTietDichVu(dv1.getMaDichVu(),maPhong);
        	        		dao.UpdateDichVuSauKhiThemBot(dv,dv.getSoLuong()+ soluongbot);
        	        		f=1;
        	        	}
        	        	else {
        	        		dao.UpdateBotChiTietDichVu(dv1, maPhong, soluong);
        	        		dao.UpdateDichVuSauKhiThemBot(dv, dv.getSoLuong()+ soluongbot);
        	        		f=1;
        	        	}
        			 break;
        		 }
        		 
        	 }
        	 if(f==0) {
        		 dao.Them(dv1);
        	 }
//        	 
        }
        }
    }
    
    private void Tim() {
    	String maDichVu = txt_MaDV.getText();
    	String tenDichVu = txt_TenDV.getText();
    	dsDichVu.clear();
    	if (tableModel.getRowCount() > 0) {
			for (int i = tableModel.getRowCount() - 1; i > -1; i--) {
				tableModel.removeRow(i);
			}
		}
    	dsDichVu = dao.searchCapNhatDichVu(maDichVu, tenDichVu);
    	for(DichVu dv: dsDichVu) {
			String[] rowData = { dv.getMaDichVu(), dv.getTenDichVu()
					, dv.getSoLuong()+"",dv.getGia()+""	};
			tableModel.addRow(rowData);

    	}
    	table_dichvu.setModel(tableModel);
    }

    private void Xoa() {
    	int select = table_dichvu1.getSelectedRow();
    	if(select == -1) {
        	JOptionPane.showMessageDialog(this, "Vui lòng chọn dịch vụ !");
        }else {
        	int f=0;
        	DichVu dv1 =dsDichVu1.get(select);
        	dsDichVu = dao.getAll();
        	for(DichVu dv : dsDichVu) {
        		if(dv.getMaDichVu().equals(dv1.getMaDichVu())) {
        			dao.UpdateDichVuSauKhiThemBot(dv1,dv.getSoLuong()+ dv1.getSoLuong());
        			dao.deleteChiTietDichVu(dv1.getMaDichVu(),maPhong);
        			f=1;
        		}
        	}
        	if(f==0) {
        		dao.Them(dv1);
        		dao.deleteChiTietDichVu(dv1.getMaDichVu(),maPhong);
        	}
        }
    	
    }
    

}
