/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.awt.Button;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.Enumeration;

import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JToggleButton;
import javax.swing.event.ChangeListener;

import DAO.ChiTietDatPhong_Dao;
import DAO.Phong_dao;
import Enitity.ChiTietDatPhong;
import Enitity.Phong;

/**
 *
 * @author vanng
 */
public class QuanLyDanhSachPhong extends javax.swing.JPanel implements ActionListener,MouseListener{

    /**
     * Creates new form QuanLyDanhSachPhong
     */
	Phong_dao ph_dao = new Phong_dao();
	ChiTietDatPhong_Dao dp_dao = new ChiTietDatPhong_Dao();
	//Tao icon
	Icon iconPhongCho = new ImageIcon("D:\\HocHanh\\HK1-2022-2023\\BTLon\\backup2\\src\\img\\phongcho.png");
	Icon iconPhongTrong = new ImageIcon("D:\\HocHanh\\HK1-2022-2023\\BTLon\\backup2\\src\\img\\phongtrong.png");
	Icon iconPhongDSD = new ImageIcon("D:\\HocHanh\\HK1-2022-2023\\BTLon\\backup2\\src\\img\\phongdangsudung.png");
    Icon iconPhongChomini = new ImageIcon("D:\\HocHanh\\HK1-2022-2023\\BTLon\\backup2\\src\\img\\phongchomini.png");
	Icon iconPhongTrongmini = new ImageIcon("D:\\HocHanh\\HK1-2022-2023\\BTLon\\backup2\\src\\img\\phongtrongmini.png");
	Icon iconPhongDSDmini = new ImageIcon("D:\\HocHanh\\HK1-2022-2023\\BTLon\\backup2\\src\\img\\phongdangsudungmini.png");
	private ButtonGroup btnGroup;
	//Tạo groupButton    ///
    public QuanLyDanhSachPhong() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        btn_datPhongCho = new javax.swing.JButton();
        btn_nhanPhongCho = new javax.swing.JButton();
        btn_datPhong1 = new javax.swing.JButton();
        btn_huyPhong = new javax.swing.JButton();
        btn_xemPhong = new javax.swing.JButton();
        btn_dichVu = new javax.swing.JButton();
        btn_tinhTien = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        rdo_phongThuong = new javax.swing.JRadioButton();
        rdo_phongVIP = new javax.swing.JRadioButton();
        jPanel20 = new javax.swing.JPanel();
        rdo_dangSD = new javax.swing.JRadioButton();
        rdo_phongCho = new javax.swing.JRadioButton();
        rdo_phongTrong = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_timKiem = new javax.swing.JTextPane();
        btn_timKiem = new javax.swing.JButton();
        btn_lamMoi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel16 = new javax.swing.JPanel();
        pnl_p1 = new javax.swing.JPanel();
        btn_iPhong1 = new javax.swing.JToggleButton();
        btn_iPhong1.setActionCommand("123");
        btn_phong1 = new javax.swing.JToggleButton();
        pnl_p2 = new javax.swing.JPanel();
        btn_iPhong2 = new JToggleButton();
        btn_phong2 = new javax.swing.JToggleButton();
        pnl_p3 = new javax.swing.JPanel();
        btn_iPhong3 = new javax.swing.JToggleButton();
        btn_phong3 = new javax.swing.JToggleButton();
        pnl_p4 = new javax.swing.JPanel();
        btn_iPhong4 = new javax.swing.JToggleButton();
        btn_phong4 = new javax.swing.JToggleButton();
        pnl_p5 = new javax.swing.JPanel();
        btn_iPhong5 = new javax.swing.JToggleButton();
        btn_phong5 = new javax.swing.JToggleButton();
        pnl_p6 = new javax.swing.JPanel();
        btn_iPhong6 = new javax.swing.JToggleButton();
        btn_phong6 = new javax.swing.JToggleButton();
        pnl_p7 = new javax.swing.JPanel();
        btn_iPhong7 = new javax.swing.JToggleButton();
        btn_phong7 = new javax.swing.JToggleButton();
        pnl_p8 = new javax.swing.JPanel();
        btn_iPhong8 = new javax.swing.JToggleButton();
        btn_phong8 = new javax.swing.JToggleButton();
        pnl_p9 = new javax.swing.JPanel();
        btn_iPhong12 = new javax.swing.JToggleButton();
        btn_phong12 = new javax.swing.JToggleButton();
        pnl_p10 = new javax.swing.JPanel();
        btn_iPhong11 = new javax.swing.JToggleButton();
        btn_phong11 = new javax.swing.JToggleButton();
        pnl_p11 = new javax.swing.JPanel();
        btn_iPhong10 = new javax.swing.JToggleButton();
        btn_phong10 = new javax.swing.JToggleButton();
        pnl_p12 = new javax.swing.JPanel();
        btn_iPhong9 = new javax.swing.JToggleButton();
        btn_phong9 = new javax.swing.JToggleButton();
        pnl_p13 = new javax.swing.JPanel();
        btn_iPhong13 = new javax.swing.JToggleButton();
        btn_phong13 = new javax.swing.JToggleButton();
        pnl_p14 = new javax.swing.JPanel();
        btn_iPhong16 = new javax.swing.JToggleButton();
        btn_phong16 = new javax.swing.JToggleButton();
        pnl_p15 = new javax.swing.JPanel();
        btn_iPhong15 = new javax.swing.JToggleButton();
        btn_phong15 = new javax.swing.JToggleButton();
        pnl_p16 = new javax.swing.JPanel();
        btn_iPhong14 = new javax.swing.JToggleButton();
        btn_phong14 = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        btn_iconCho = new javax.swing.JButton();
        btn_iconCho.setIcon(iconPhongChomini);
        btn_iconSD = new javax.swing.JButton();
        btn_iconSD.setIcon(iconPhongDSDmini);
        btn_iconTrong = new javax.swing.JButton();
        btn_iconTrong.setIcon(iconPhongTrongmini);
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        //
     
       setPreferredSize(new java.awt.Dimension(1000, 600));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_datPhongCho.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_datPhongCho.setText("Đặt phòng chờ");
        btn_datPhongCho.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_datPhongCho.setEnabled(false);
        btn_datPhongCho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_datPhongChoActionPerformed(evt);
            }
        });

        btn_nhanPhongCho.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_nhanPhongCho.setText("Nhận phòng chờ");
        btn_nhanPhongCho.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_nhanPhongCho.setEnabled(false);
        btn_nhanPhongCho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nhanPhongChoActionPerformed(evt);
            }
        });

        btn_datPhong1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_datPhong1.setText("Đặt phòng");
        btn_datPhong1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_datPhong1.setEnabled(false);
        btn_datPhong1.addActionListener(this);
        btn_datPhong1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_datPhong1ActionPerformed(evt);
            }
        });

        btn_huyPhong.setText("Hủy phòng");
        btn_huyPhong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_huyPhong.setEnabled(false);
        btn_huyPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_huyPhongActionPerformed(evt);
            }
        });

        btn_xemPhong.setText("Xem phòng");
        btn_xemPhong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_xemPhong.setEnabled(false);
        btn_xemPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xemPhongActionPerformed(evt);
            }
        });

        btn_dichVu.setText("Dịch vụ");
        btn_dichVu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_dichVu.setEnabled(false);
        btn_dichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dichVuActionPerformed(evt);
            }
        });

        btn_tinhTien.setText("Tính tiền");
        btn_tinhTien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_tinhTien.setEnabled(false);
        btn_tinhTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tinhTienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_dichVu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_xemPhong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_huyPhong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_nhanPhongCho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(btn_datPhongCho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_datPhong1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_tinhTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btn_datPhong1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_datPhongCho, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_nhanPhongCho, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_huyPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_xemPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_dichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_tinhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        jPanel22.setBorder(javax.swing.BorderFactory.createTitledBorder("Bộ lọc"));

        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder("Loại phòng"));

        buttonGroup1.add(rdo_phongThuong);
        rdo_phongThuong.setText("Phòng thường");
        rdo_phongThuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_phongThuongActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdo_phongVIP);
        rdo_phongVIP.setText("Phòng VIP");
        rdo_phongVIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_phongVIPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdo_phongThuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdo_phongVIP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdo_phongThuong)
                    .addComponent(rdo_phongVIP))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel20.setBorder(javax.swing.BorderFactory.createTitledBorder("Trạng thái"));

        buttonGroup2.add(rdo_dangSD);
        rdo_dangSD.setText("Đang sử dụng");
        rdo_dangSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_dangSDActionPerformed(evt);
            }
        });

        buttonGroup2.add(rdo_phongCho);
        rdo_phongCho.setText("Phòng chờ");
        rdo_phongCho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_phongChoActionPerformed(evt);
            }
        });

        buttonGroup2.add(rdo_phongTrong);
        rdo_phongTrong.setText("Phòng trống");
        rdo_phongTrong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_phongTrongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addComponent(rdo_dangSD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdo_phongCho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdo_phongTrong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdo_dangSD)
                    .addComponent(rdo_phongCho)
                    .addComponent(rdo_phongTrong))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Tìm kiếm");

        jScrollPane2.setViewportView(txt_timKiem);

        btn_timKiem.setIcon(new javax.swing.ImageIcon("D:\\HocHanh\\HK1-2022-2023\\PTUD\\karaoke\\img\\search-icon-16.png")); // NOI18N
        btn_timKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timKiemActionPerformed(evt);
            }
        });

        btn_lamMoi.setText("Làm mới");
        btn_lamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lamMoiActionPerformed(evt);
            }
        });

        jScrollPane1.setPreferredSize(new java.awt.Dimension(831, 633));

        jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pnl_p1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_iPhong1.setBorder(null);
        btn_iPhong1.setPreferredSize(new java.awt.Dimension(140, 140));
        btn_iPhong1.setActionCommand("PH0001");
      //Set icon cho phòng 1
        Phong p1 = ph_dao.findbyId("PH0001");	
    	if(p1.getTrangThai().equals("Phòng trống"))
    		btn_iPhong1.setIcon(iconPhongTrong);
    	else if(p1.getTrangThai().equals("Phòng đang sử dụng"))
    		btn_iPhong1.setIcon(iconPhongDSD);
    	else if(p1.getTrangThai().equals("Phòng chờ")) 
    		btn_iPhong1.setIcon(iconPhongCho);
    	///
    	btn_iPhong1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iPhong1ActionPerformed(evt);
            }
        });

        btn_phong1.setText("Phòng 1");
        btn_phong1.setActionCommand("Phòng 1");
        btn_phong1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_phong1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_phong1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_p1Layout = new javax.swing.GroupLayout(pnl_p1);
        pnl_p1.setLayout(pnl_p1Layout);
        pnl_p1Layout.setHorizontalGroup(
            pnl_p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_p1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_phong1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_iPhong1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnl_p1Layout.setVerticalGroup(
            pnl_p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_p1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_iPhong1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_phong1)
                .addContainerGap())
        );

        pnl_p2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      
        btn_iPhong2.setBorder(null);
        btn_iPhong2.setActionCommand("PH0002");
        add(btn_iPhong2);
        btn_iPhong2.setPreferredSize(new java.awt.Dimension(140, 140));
        //Set icon cho phòng 1
        Phong p2 = ph_dao.findbyId("PH0002");	
    	if(p2.getTrangThai().equals("Phòng trống"))
    		btn_iPhong2.setIcon(iconPhongTrong);
    	else if(p2.getTrangThai().equals("Phòng đang sử dụng"))
    		btn_iPhong2.setIcon(iconPhongDSD);
    	else if(p2.getTrangThai().equals("Phòng chờ")) 
    		btn_iPhong2.setIcon(iconPhongCho);
    	///
        btn_iPhong2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iPhong2ActionPerformed(evt);
            }
        });

        btn_phong2.setText("Phòng 2");
        btn_phong2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_phong2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_phong2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_p2Layout = new javax.swing.GroupLayout(pnl_p2);
        pnl_p2.setLayout(pnl_p2Layout);
        pnl_p2Layout.setHorizontalGroup(
            pnl_p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_p2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_phong2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_iPhong2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnl_p2Layout.setVerticalGroup(
            pnl_p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_p2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_iPhong2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_phong2)
                .addContainerGap())
        );

        pnl_p3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl_p3.setPreferredSize(new java.awt.Dimension(150, 180));

        btn_iPhong3.setBorder(null);
        btn_iPhong3.setPreferredSize(new java.awt.Dimension(140, 140));
      //Set icon cho phòng 3
        Phong p3 = ph_dao.findbyId("PH0003");	
    	if(p3.getTrangThai().equals("Phòng trống"))
    		btn_iPhong3.setIcon(iconPhongTrong);
    	else if(p3.getTrangThai().equals("Phòng đang sử dụng"))
    		btn_iPhong3.setIcon(iconPhongDSD);
    	else if(p3.getTrangThai().equals("Phòng chờ")) 
    		btn_iPhong3.setIcon(iconPhongCho);
    	////////////////////////////////////////////////////////
        btn_iPhong3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iPhong3ActionPerformed(evt);
            }
        });

        btn_phong3.setText("Phòng 3");
        btn_phong3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_phong3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_phong3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_p3Layout = new javax.swing.GroupLayout(pnl_p3);
        pnl_p3.setLayout(pnl_p3Layout);
        pnl_p3Layout.setHorizontalGroup(
            pnl_p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_p3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_phong3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_iPhong3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnl_p3Layout.setVerticalGroup(
            pnl_p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_p3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_iPhong3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_phong3)
                .addContainerGap())
        );

        pnl_p4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl_p4.setPreferredSize(new java.awt.Dimension(150, 180));

        btn_iPhong4.setBorder(null);
        btn_iPhong4.setPreferredSize(new java.awt.Dimension(140, 140));
      //Set icon cho phòng 4
        Phong p4 = ph_dao.findbyId("PH0004");	
    	if(p4.getTrangThai().equals("Phòng trống"))
    		btn_iPhong4.setIcon(iconPhongTrong);
    	else if(p4.getTrangThai().equals("Phòng đang sử dụng"))
    		btn_iPhong4.setIcon(iconPhongDSD);
    	else if(p4.getTrangThai().equals("Phòng chờ")) 
    		btn_iPhong4.setIcon(iconPhongCho);
    	////////////////////////////////////////////////////////
        btn_iPhong4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iPhong4ActionPerformed(evt);
            }
        });

        btn_phong4.setText("Phòng 4");
        btn_phong4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_phong4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_phong4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_p4Layout = new javax.swing.GroupLayout(pnl_p4);
        pnl_p4.setLayout(pnl_p4Layout);
        pnl_p4Layout.setHorizontalGroup(
            pnl_p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_p4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_phong4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_iPhong4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnl_p4Layout.setVerticalGroup(
            pnl_p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_p4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_iPhong4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_phong4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_p5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl_p5.setPreferredSize(new java.awt.Dimension(150, 180));

        btn_iPhong5.setBorder(null);
        btn_iPhong5.setPreferredSize(new java.awt.Dimension(140, 140));
      //Set icon cho phòng 5
        Phong p5 = ph_dao.findbyId("PH0005");	
    	if(p5.getTrangThai().equals("Phòng trống"))
    		btn_iPhong5.setIcon(iconPhongTrong);
    	else if(p5.getTrangThai().equals("Phòng đang sử dụng"))
    		btn_iPhong5.setIcon(iconPhongDSD);
    	else if(p5.getTrangThai().equals("Phòng chờ")) 
    		btn_iPhong5.setIcon(iconPhongCho);
    	////////////////////////////////////////////////////////
        btn_iPhong5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iPhong5ActionPerformed(evt);
            }
        });

        btn_phong5.setText("Phòng 5");
        btn_phong5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_phong5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_phong5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_p5Layout = new javax.swing.GroupLayout(pnl_p5);
        pnl_p5.setLayout(pnl_p5Layout);
        pnl_p5Layout.setHorizontalGroup(
            pnl_p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_p5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_iPhong5, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(btn_phong5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnl_p5Layout.setVerticalGroup(
            pnl_p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_p5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_iPhong5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_phong5)
                .addContainerGap())
        );

        pnl_p6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl_p6.setPreferredSize(new java.awt.Dimension(150, 180));

        btn_iPhong6.setBorder(null);
        btn_iPhong6.setPreferredSize(new java.awt.Dimension(140, 140));
        //Set icon cho phòng 6 ////////////////////////////////////////////
        Phong p6 = ph_dao.findbyId("PH0006");	
    	if(p6.getTrangThai().equals("Phòng trống"))
    		btn_iPhong6.setIcon(iconPhongTrong);
    	else if(p6.getTrangThai().equals("Phòng đang sử dụng"))
    		btn_iPhong6.setIcon(iconPhongDSD);
    	else if(p6.getTrangThai().equals("Phòng chờ")) 
    		btn_iPhong6.setIcon(iconPhongCho);
    	////////////////////////////////////////////////////////
        btn_iPhong6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iPhong6ActionPerformed(evt);
            }
        });

        btn_phong6.setText("Phòng 6");
        btn_phong6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_phong6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_phong6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_p6Layout = new javax.swing.GroupLayout(pnl_p6);
        pnl_p6.setLayout(pnl_p6Layout);
        pnl_p6Layout.setHorizontalGroup(
            pnl_p6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_p6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_p6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_iPhong6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_phong6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnl_p6Layout.setVerticalGroup(
            pnl_p6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_p6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_iPhong6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_phong6)
                .addContainerGap())
        );

        pnl_p7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl_p7.setPreferredSize(new java.awt.Dimension(150, 180));

        btn_iPhong7.setBorder(null);
        btn_iPhong7.setPreferredSize(new java.awt.Dimension(140, 140));
        //Set icon cho phòng 7 ////////////////////////////////////////////
        Phong p7 = ph_dao.findbyId("PH0007");	
    	if(p7.getTrangThai().equals("Phòng trống"))
    		btn_iPhong7.setIcon(iconPhongTrong);
    	else if(p7.getTrangThai().equals("Phòng đang sử dụng"))
    		btn_iPhong7.setIcon(iconPhongDSD);
    	else if(p7.getTrangThai().equals("Phòng chờ")) 
    		btn_iPhong7.setIcon(iconPhongCho);
    	////////////////////////////////////////////////////////
        btn_iPhong7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iPhong7ActionPerformed(evt);
            }
        });

        btn_phong7.setText("Phòng 7");
        btn_phong7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_phong7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_phong7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_p7Layout = new javax.swing.GroupLayout(pnl_p7);
        pnl_p7.setLayout(pnl_p7Layout);
        pnl_p7Layout.setHorizontalGroup(
            pnl_p7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_p7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_p7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_iPhong7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_phong7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnl_p7Layout.setVerticalGroup(
            pnl_p7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_p7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_iPhong7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_phong7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_p8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl_p8.setPreferredSize(new java.awt.Dimension(150, 180));

        btn_iPhong8.setBorder(null);
        btn_iPhong8.setPreferredSize(new java.awt.Dimension(140, 140));
        //Set icon cho phòng 8 ////////////////////////////////////////////
        Phong p8 = ph_dao.findbyId("PH0008");	
    	if(p8.getTrangThai().equals("Phòng trống"))
    		btn_iPhong8.setIcon(iconPhongTrong);
    	else if(p8.getTrangThai().equals("Phòng đang sử dụng"))
    		btn_iPhong8.setIcon(iconPhongDSD);
    	else if(p8.getTrangThai().equals("Phòng chờ")) 
    		btn_iPhong8.setIcon(iconPhongCho);
    	////////////////////////////////////////////////////////
        btn_iPhong8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iPhong8ActionPerformed(evt);
            }
        });

        btn_phong8.setText("Phòng 8");
        btn_phong8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_phong8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_phong8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_p8Layout = new javax.swing.GroupLayout(pnl_p8);
        pnl_p8.setLayout(pnl_p8Layout);
        pnl_p8Layout.setHorizontalGroup(
            pnl_p8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_p8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_p8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_phong8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnl_p8Layout.createSequentialGroup()
                        .addComponent(btn_iPhong8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6)))
                .addContainerGap())
        );
        pnl_p8Layout.setVerticalGroup(
            pnl_p8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_p8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_iPhong8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_phong8)
                .addContainerGap())
        );

        pnl_p9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl_p9.setPreferredSize(new java.awt.Dimension(150, 180));

        btn_iPhong12.setBorder(null);
        btn_iPhong12.setPreferredSize(new java.awt.Dimension(140, 140));
        //Set icon cho phòng 12 ////////////////////////////////////////////
        Phong p12 = ph_dao.findbyId("PH0012");	
    	if(p12.getTrangThai().equals("Phòng trống"))
    		btn_iPhong12.setIcon(iconPhongTrong);
    	else if(p12.getTrangThai().equals("Phòng đang sử dụng"))
    		btn_iPhong12.setIcon(iconPhongDSD);
    	else if(p12.getTrangThai().equals("Phòng chờ")) 
    		btn_iPhong12.setIcon(iconPhongCho);
    	////////////////////////////////////////////////////////
        btn_iPhong12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iPhong12ActionPerformed(evt);
            }
        });

        btn_phong12.setText("Phòng 12");
        btn_phong12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_phong12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_phong12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_p9Layout = new javax.swing.GroupLayout(pnl_p9);
        pnl_p9.setLayout(pnl_p9Layout);
        pnl_p9Layout.setHorizontalGroup(
            pnl_p9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_p9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_p9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_iPhong12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_phong12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnl_p9Layout.setVerticalGroup(
            pnl_p9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_p9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_iPhong12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btn_phong12)
                .addContainerGap())
        );

        pnl_p10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl_p10.setPreferredSize(new java.awt.Dimension(150, 180));

        btn_iPhong11.setBorder(null);
        btn_iPhong11.setPreferredSize(new java.awt.Dimension(140, 140));
        //Set icon cho phòng 11 ////////////////////////////////////////////
        Phong p11 = ph_dao.findbyId("PH0011");	
    	if(p11.getTrangThai().equals("Phòng trống"))
    		btn_iPhong11.setIcon(iconPhongTrong);
    	else if(p11.getTrangThai().equals("Phòng đang sử dụng"))
    		btn_iPhong11.setIcon(iconPhongDSD);
    	else if(p11.getTrangThai().equals("Phòng chờ")) 
    		btn_iPhong11.setIcon(iconPhongCho);
    	////////////////////////////////////////////////////////
        btn_iPhong11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iPhong11ActionPerformed(evt);
            }
        });

        btn_phong11.setText("Phòng 11");
        btn_phong11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_phong11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_phong11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_p10Layout = new javax.swing.GroupLayout(pnl_p10);
        pnl_p10.setLayout(pnl_p10Layout);
        pnl_p10Layout.setHorizontalGroup(
            pnl_p10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_p10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_p10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_iPhong11, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(btn_phong11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnl_p10Layout.setVerticalGroup(
            pnl_p10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_p10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_iPhong11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_phong11)
                .addContainerGap())
        );

        pnl_p11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl_p11.setPreferredSize(new java.awt.Dimension(150, 180));

        btn_iPhong10.setBorder(null);
        btn_iPhong10.setPreferredSize(new java.awt.Dimension(140, 140));
        //Set icon cho phòng 10 ////////////////////////////////////////////
        Phong p10 = ph_dao.findbyId("PH0010");	
    	if(p10.getTrangThai().equals("Phòng trống"))
    		btn_iPhong10.setIcon(iconPhongTrong);
    	else if(p10.getTrangThai().equals("Phòng đang sử dụng"))
    		btn_iPhong10.setIcon(iconPhongDSD);
    	else if(p10.getTrangThai().equals("Phòng chờ")) 
    		btn_iPhong10.setIcon(iconPhongCho);
    	////////////////////////////////////////////////////////
        btn_iPhong10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iPhong10ActionPerformed(evt);
            }
        });

        btn_phong10.setText("Phòng 10");
        btn_phong10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_phong10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_phong10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_p11Layout = new javax.swing.GroupLayout(pnl_p11);
        pnl_p11.setLayout(pnl_p11Layout);
        pnl_p11Layout.setHorizontalGroup(
            pnl_p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_p11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_phong10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_iPhong10, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnl_p11Layout.setVerticalGroup(
            pnl_p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_p11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_iPhong10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_phong10)
                .addContainerGap())
        );

        pnl_p12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl_p12.setPreferredSize(new java.awt.Dimension(150, 180));

        btn_iPhong9.setBorder(null);
        btn_iPhong9.setPreferredSize(new java.awt.Dimension(140, 140));
        //Set icon cho phòng 9 ////////////////////////////////////////////
        Phong p9 = ph_dao.findbyId("PH0009");	
    	if(p9.getTrangThai().equals("Phòng trống"))
    		btn_iPhong9.setIcon(iconPhongTrong);
    	else if(p9.getTrangThai().equals("Phòng đang sử dụng"))
    		btn_iPhong9.setIcon(iconPhongDSD);
    	else if(p9.getTrangThai().equals("Phòng chờ")) 
    		btn_iPhong9.setIcon(iconPhongCho);
    	////////////////////////////////////////////////////////
        btn_iPhong9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iPhong9ActionPerformed(evt);
            }
        });

        btn_phong9.setText("Phòng 9");
        btn_phong9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_phong9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_phong9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_p12Layout = new javax.swing.GroupLayout(pnl_p12);
        pnl_p12.setLayout(pnl_p12Layout);
        pnl_p12Layout.setHorizontalGroup(
            pnl_p12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_p12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_p12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_iPhong9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_phong9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnl_p12Layout.setVerticalGroup(
            pnl_p12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_p12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_iPhong9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_phong9)
                .addContainerGap())
        );

        pnl_p13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl_p13.setPreferredSize(new java.awt.Dimension(150, 180));

        btn_iPhong13.setBorder(null);
        btn_iPhong13.setPreferredSize(new java.awt.Dimension(140, 140));
        //Set icon cho phòng 13 ////////////////////////////////////////////
        Phong p13 = ph_dao.findbyId("PH0013");	
    	if(p13.getTrangThai().equals("Phòng trống"))
    		btn_iPhong13.setIcon(iconPhongTrong);
    	else if(p13.getTrangThai().equals("Phòng đang sử dụng"))
    		btn_iPhong13.setIcon(iconPhongDSD);
    	else if(p13.getTrangThai().equals("Phòng chờ")) 
    		btn_iPhong13.setIcon(iconPhongCho);
    	////////////////////////////////////////////////////////
        btn_iPhong13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iPhong13ActionPerformed(evt);
            }
        });

        btn_phong13.setText("Phòng 13");
        btn_phong13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_phong13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_phong13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_p13Layout = new javax.swing.GroupLayout(pnl_p13);
        pnl_p13.setLayout(pnl_p13Layout);
        pnl_p13Layout.setHorizontalGroup(
            pnl_p13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_p13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_p13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_iPhong13, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(btn_phong13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnl_p13Layout.setVerticalGroup(
            pnl_p13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_p13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_iPhong13, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_phong13)
                .addContainerGap())
        );

        pnl_p14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl_p14.setPreferredSize(new java.awt.Dimension(150, 180));

        btn_iPhong16.setBorder(null);
        btn_iPhong16.setPreferredSize(new java.awt.Dimension(140, 140));
        //Set icon cho phòng 13 ////////////////////////////////////////////
        Phong p16 = ph_dao.findbyId("PH0016");	
    	if(p16.getTrangThai().equals("Phòng trống"))
    		btn_iPhong16.setIcon(iconPhongTrong);
    	else if(p16.getTrangThai().equals("Phòng đang sử dụng"))
    		btn_iPhong16.setIcon(iconPhongDSD);
    	else if(p16.getTrangThai().equals("Phòng chờ")) 
    		btn_iPhong16.setIcon(iconPhongCho);
    	////////////////////////////////////////////////////////
        btn_iPhong16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iPhong16ActionPerformed(evt);
            }
        });

        btn_phong16.setText("Phòng 16");
        btn_phong16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_phong16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_phong16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_p14Layout = new javax.swing.GroupLayout(pnl_p14);
        pnl_p14.setLayout(pnl_p14Layout);
        pnl_p14Layout.setHorizontalGroup(
            pnl_p14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_p14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_p14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_iPhong16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_phong16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnl_p14Layout.setVerticalGroup(
            pnl_p14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_p14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_iPhong16, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_phong16)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pnl_p15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl_p15.setPreferredSize(new java.awt.Dimension(150, 180));

        btn_iPhong15.setBorder(null);
        btn_iPhong15.setPreferredSize(new java.awt.Dimension(140, 140));
      //Set icon cho phòng 15 ////////////////////////////////////////////
        Phong p15 = ph_dao.findbyId("PH0015");	
    	if(p15.getTrangThai().equals("Phòng trống"))
    		btn_iPhong15.setIcon(iconPhongTrong);
    	else if(p15.getTrangThai().equals("Phòng đang sử dụng"))
    		btn_iPhong15.setIcon(iconPhongDSD);
    	else if(p15.getTrangThai().equals("Phòng chờ")) 
    		btn_iPhong15.setIcon(iconPhongCho);
    	////////////////////////////////////////////////////////
        btn_iPhong15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iPhong15ActionPerformed(evt);
            }
        });

        btn_phong15.setText("Phòng 15");
        btn_phong15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_phong15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_phong15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_p15Layout = new javax.swing.GroupLayout(pnl_p15);
        pnl_p15.setLayout(pnl_p15Layout);
        pnl_p15Layout.setHorizontalGroup(
            pnl_p15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_p15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_p15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_iPhong15, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(btn_phong15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnl_p15Layout.setVerticalGroup(
            pnl_p15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_p15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_iPhong15, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_phong15)
                .addContainerGap())
        );

        pnl_p16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl_p16.setPreferredSize(new java.awt.Dimension(150, 180));

        btn_iPhong14.setBorder(null);
        btn_iPhong14.setPreferredSize(new java.awt.Dimension(140, 140));
      //Set icon cho phòng 14 ////////////////////////////////////////////
        Phong p14 = ph_dao.findbyId("PH0014");	
    	if(p14.getTrangThai().equals("Phòng trống"))
    		btn_iPhong14.setIcon(iconPhongTrong);
    	else if(p14.getTrangThai().equals("Phòng đang sử dụng"))
    		btn_iPhong14.setIcon(iconPhongDSD);
    	else if(p14.getTrangThai().equals("Phòng chờ")) 
    		btn_iPhong14.setIcon(iconPhongCho);
    	////////////////////////////////////////////////////////
        btn_iPhong14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iPhong14ActionPerformed(evt);
            }
        });

        btn_phong14.setText("Phòng 14");
        btn_phong14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_phong14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_phong14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_p16Layout = new javax.swing.GroupLayout(pnl_p16);
        pnl_p16.setLayout(pnl_p16Layout);
        pnl_p16Layout.setHorizontalGroup(
            pnl_p16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_p16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_p16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_iPhong14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_phong14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnl_p16Layout.setVerticalGroup(
            pnl_p16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_p16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_iPhong14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_phong14)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_p5, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(pnl_p1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_p12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(pnl_p13, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_p11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(pnl_p6, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(pnl_p16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(pnl_p2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_p10, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(pnl_p7, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(pnl_p15, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(pnl_p3, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pnl_p9, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(pnl_p8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(pnl_p4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                        .addGap(2, 2, 2))
                    .addComponent(pnl_p14, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_p4, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(pnl_p1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_p3, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(pnl_p2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnl_p5, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(pnl_p6, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(pnl_p7, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(pnl_p8, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnl_p9, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(pnl_p11, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(pnl_p12, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(pnl_p10, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnl_p16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_p15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_p14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_p13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel16);

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_lamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(btn_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_lamMoi)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                .addContainerGap())
        );

        btn_iconCho.setBorder(null);
        btn_iconCho.setPreferredSize(new java.awt.Dimension(30, 30));

        btn_iconSD.setBorder(null);
        btn_iconSD.setPreferredSize(new java.awt.Dimension(30, 30));

        btn_iconTrong.setBorder(null);
        btn_iconTrong.setPreferredSize(new java.awt.Dimension(30, 30));

        jLabel2.setText("Phòng đang sử dụng");

        jLabel3.setText("Phòng chờ");

        jLabel4.setText("Phòng trống ");
        jLabel4.setAlignmentX(0.5F);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_iconCho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_iconSD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_iconTrong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_iconCho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(btn_iconSD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_iconTrong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(140, 140, 140))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 445, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))))
            
        );
        btn_phong1.setActionCommand("PH0001");
    	btn_phong2.setActionCommand("PH0002");
    	btn_phong3.setActionCommand("PH0003");
    	btn_phong4.setActionCommand("PH0004");
    	btn_phong5.setActionCommand("PH0005");
    	btn_phong6.setActionCommand("PH0006");
    	btn_phong7.setActionCommand("PH0007");
    	btn_phong8.setActionCommand("PH0008");
    	btn_phong9.setActionCommand("PH0009");
    	btn_phong10.setActionCommand("PH0010");
    	btn_phong11.setActionCommand("PH0011");
    	btn_phong12.setActionCommand("PH0012");
    	btn_phong13.setActionCommand("PH0013");
    	btn_phong14.setActionCommand("PH0014");
    	btn_phong15.setActionCommand("PH0015");
    	btn_phong16.setActionCommand("PH0016");
    	
    	btn_iPhong1.setActionCommand("PH0001");
    	btn_iPhong2.setActionCommand("PH0002");
    	btn_iPhong3.setActionCommand("PH0003");
    	btn_iPhong4.setActionCommand("PH0004");
    	btn_iPhong5.setActionCommand("PH0005");
    	btn_iPhong6.setActionCommand("PH0006");
    	btn_iPhong7.setActionCommand("PH0007");
    	btn_iPhong8.setActionCommand("PH0008");
    	btn_iPhong9.setActionCommand("PH0009");
    	btn_iPhong10.setActionCommand("PH0010");
    	btn_iPhong11.setActionCommand("PH0011");
    	btn_iPhong12.setActionCommand("PH0012");
    	btn_iPhong13.setActionCommand("PH0013");
    	btn_iPhong14.setActionCommand("PH0014");
    	btn_iPhong15.setActionCommand("PH0015");
    	btn_iPhong16.setActionCommand("PH0016");
    	
    	btnGroup = new ButtonGroup();
    	btnGroup.add(btn_phong1);
    	btnGroup.add(btn_phong2);
    	btnGroup.add(btn_phong3);
    	btnGroup.add(btn_phong4);
    	btnGroup.add(btn_phong5);
    	btnGroup.add(btn_phong6);
    	btnGroup.add(btn_phong7);
    	btnGroup.add(btn_phong8);
    	btnGroup.add(btn_phong9);
    	btnGroup.add(btn_phong10);
    	btnGroup.add(btn_phong11);
    	btnGroup.add(btn_phong12);
    	btnGroup.add(btn_phong13);
    	btnGroup.add(btn_phong14);
    	btnGroup.add(btn_phong15);
    	btnGroup.add(btn_phong16);
    	
    	btnGroup.add(btn_iPhong1);
    	btnGroup.add(btn_iPhong2);
    	btnGroup.add(btn_iPhong3);
    	btnGroup.add(btn_iPhong4);
    	btnGroup.add(btn_iPhong5);
    	btnGroup.add(btn_iPhong6);
    	btnGroup.add(btn_iPhong7);
    	btnGroup.add(btn_iPhong8);
    	btnGroup.add(btn_iPhong9);
    	btnGroup.add(btn_iPhong10);
    	btnGroup.add(btn_iPhong11);
    	btnGroup.add(btn_iPhong12);
    	btnGroup.add(btn_iPhong13);
    	btnGroup.add(btn_iPhong14);
    	btnGroup.add(btn_iPhong15);
    	btnGroup.add(btn_iPhong16);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_timKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_timKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_timKiemActionPerformed

    private void btn_huyPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_huyPhongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_huyPhongActionPerformed

    private void btn_datPhong1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_datPhong1ActionPerformed
//    	String ex ="DP";
//		int min = 9999;
//		int max = 1000;
//		int random_int = (int)(Math.random() * (max - min + 1) + min);
//    	String chiTietDatPhong=ex+random_int; 
//    	String ma = btnGroup.getSelection().getActionCommand();
//    	Phong p = ph_dao.findbyId(ma);
//    	ChiTietDatPhong dp = new ChiTietDatPhong(chiTietDatPhong, null, null, p);
//    	dp_dao.them(dp);
    	System.out.println(btnGroup.getSelection().getActionCommand());
    	
    	
    	
    }//GEN-LAST:event_btn_datPhong1ActionPerformed
    
    
    private void btn_nhanPhongChoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nhanPhongChoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_nhanPhongChoActionPerformed

    private void btn_datPhongChoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_datPhongChoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_datPhongChoActionPerformed

    private void btn_phong1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_phong1ActionPerformed
      setEnabledbyId("PH0001");
    }

    private void btn_iPhong1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iPhong1ActionPerformed
    	setEnabledbyId("PH0001");
    }//GEN-LAST:event_btn_iPhong1ActionPerformed

    private void btn_iPhong3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iPhong3ActionPerformed
    	setEnabledbyId("PH0003");
    }//GEN-LAST:event_btn_iPhong3ActionPerformed

    private void btn_iPhong15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iPhong15ActionPerformed
        // TODO add your handling code here:
    	setEnabledbyId("PH0015");
    }//GEN-LAST:event_btn_iPhong15ActionPerformed

    private void btn_iPhong2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iPhong2ActionPerformed
        // TODO add your handling code here:
    	setEnabledbyId("PH0002");
    }//GEN-LAST:event_btn_iPhong2ActionPerformed

    private void btn_phong2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_phong2ActionPerformed
        // TODO add your handling code here:
    	setEnabledbyId("PH0002");
    }//GEN-LAST:event_btn_phong2ActionPerformed

    private void btn_phong3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_phong3ActionPerformed
        // TODO add your handling code here:
    	setEnabledbyId("PH0003");
    }//GEN-LAST:event_btn_phong3ActionPerformed

    private void btn_iPhong4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iPhong4ActionPerformed
        // TODO add your handling code here:
    	setEnabledbyId("PH0004");
    }//GEN-LAST:event_btn_iPhong4ActionPerformed

    private void btn_phong4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_phong4ActionPerformed
        // TODO add your handling code here:
    	setEnabledbyId("PH0004");
    }//GEN-LAST:event_btn_phong4ActionPerformed

    private void btn_iPhong5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iPhong5ActionPerformed
        // TODO add your handling code here:
    	setEnabledbyId("PH0005");
    }//GEN-LAST:event_btn_iPhong5ActionPerformed

    private void btn_phong5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_phong5ActionPerformed
        // TODO add your handling code here:
    	setEnabledbyId("PH0005");
    }//GEN-LAST:event_btn_phong5ActionPerformed

    private void btn_iPhong6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iPhong6ActionPerformed
        // TODO add your handling code here:
    	setEnabledbyId("PH0006");
    }//GEN-LAST:event_btn_iPhong6ActionPerformed

    private void btn_phong6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_phong6ActionPerformed
        // TODO add your handling code here:
    	setEnabledbyId("PH0006");
    }//GEN-LAST:event_btn_phong6ActionPerformed

    private void btn_iPhong7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iPhong7ActionPerformed
        // TODO add your handling code here:
    	setEnabledbyId("PH0007");
    }//GEN-LAST:event_btn_iPhong7ActionPerformed

    private void btn_phong7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_phong7ActionPerformed
        // TODO add your handling code here:
    	setEnabledbyId("PH0007");
    }//GEN-LAST:event_btn_phong7ActionPerformed

    private void btn_iPhong8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iPhong8ActionPerformed
        // TODO add your handling code here:
    	setEnabledbyId("PH0008");
    }//GEN-LAST:event_btn_iPhong8ActionPerformed

    private void btn_phong8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_phong8ActionPerformed
        // TODO add your handling code here:
    	setEnabledbyId("PH0008");
    }//GEN-LAST:event_btn_phong8ActionPerformed

    private void btn_iPhong12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iPhong12ActionPerformed
        // TODO add your handling code here:
    	setEnabledbyId("PH0012");
    }//GEN-LAST:event_btn_iPhong12ActionPerformed

    private void btn_phong12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_phong12ActionPerformed
        // TODO add your handling code here:
    	setEnabledbyId("PH0012");
    }//GEN-LAST:event_btn_phong12ActionPerformed

    private void btn_iPhong11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iPhong11ActionPerformed
        // TODO add your handling code here:
    	setEnabledbyId("PH0011");
    }//GEN-LAST:event_btn_iPhong11ActionPerformed

    private void btn_phong11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_phong11ActionPerformed
        // TODO add your handling code here:
    	setEnabledbyId("PH0011");
    }//GEN-LAST:event_btn_phong11ActionPerformed

    private void btn_iPhong10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iPhong10ActionPerformed
        // TODO add your handling code here:
    	setEnabledbyId("PH0010");
    }//GEN-LAST:event_btn_iPhong10ActionPerformed

    private void btn_phong10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_phong10ActionPerformed
        // TODO add your handling code here:
    	setEnabledbyId("PH0010");
    }//GEN-LAST:event_btn_phong10ActionPerformed

    private void btn_iPhong9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iPhong9ActionPerformed
        // TODO add your handling code here:
    	setEnabledbyId("PH0009");
    }//GEN-LAST:event_btn_iPhong9ActionPerformed

    private void btn_phong9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_phong9ActionPerformed
        // TODO add your handling code here:
    	setEnabledbyId("PH0009");
    }//GEN-LAST:event_btn_phong9ActionPerformed

    private void btn_iPhong13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iPhong13ActionPerformed
        // TODO add your handling code here:
    	setEnabledbyId("PH0013");
    }//GEN-LAST:event_btn_iPhong13ActionPerformed

    private void btn_phong13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_phong13ActionPerformed
        // TODO add your handling code here:
    	setEnabledbyId("PH0013");
    }//GEN-LAST:event_btn_phong13ActionPerformed

    private void btn_iPhong16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iPhong16ActionPerformed
        // TODO add your handling code here:
    	setEnabledbyId("PH0016");
    }//GEN-LAST:event_btn_iPhong16ActionPerformed

    private void btn_phong16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_phong16ActionPerformed
        // TODO add your handling code here:
    	setEnabledbyId("PH0016");
    }//GEN-LAST:event_btn_phong16ActionPerformed

    private void btn_phong15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_phong15ActionPerformed
        // TODO add your handling code here:
    	setEnabledbyId("PH0015");
    }//GEN-LAST:event_btn_phong15ActionPerformed

    private void btn_iPhong14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iPhong14ActionPerformed
        // TODO add your handling code here:
    	setEnabledbyId("PH0014");
    }//GEN-LAST:event_btn_iPhong14ActionPerformed

    private void btn_phong14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_phong14ActionPerformed
        // TODO add your handling code here:
    	setEnabledbyId("PH0014");
    }//GEN-LAST:event_btn_phong14ActionPerformed

    private void btn_xemPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xemPhongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_xemPhongActionPerformed

    private void btn_dichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dichVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dichVuActionPerformed

    private void btn_tinhTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tinhTienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tinhTienActionPerformed

    private void rdo_phongThuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_phongThuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo_phongThuongActionPerformed

    private void rdo_phongVIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_phongVIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo_phongVIPActionPerformed

    private void rdo_dangSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_dangSDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo_dangSDActionPerformed

    private void rdo_phongChoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_phongChoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo_phongChoActionPerformed

    private void rdo_phongTrongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_phongTrongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo_phongTrongActionPerformed

    private void btn_timKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_timKiemActionPerformed

    private void btn_lamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lamMoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_lamMoiActionPerformed
    public void listSetEnabled() {
    	ArrayList<Phong> listPhong = ph_dao.getAllPhong();
    	for(Phong p : listPhong) {
    		setEnabledbyId(p.getMaPhong());
    	}
    }
    public void setEnabledbyId(String maPhong){
    	Phong p = ph_dao.findbyId(maPhong);
    	if(p.getTrangThai().equals("Phòng trống")) {
    		btn_datPhong1.setEnabled(true);
    		btn_datPhongCho.setEnabled(true);
    		btn_xemPhong.setEnabled(true);
    		
    		btn_dichVu.setEnabled(false);
    		btn_tinhTien.setEnabled(false);	
    		btn_nhanPhongCho.setEnabled(false);
    		btn_huyPhong.setEnabled(false);
    	}
    	else if(p.getTrangThai().equals("Phòng đang sử dụng")) {
    		btn_dichVu.setEnabled(true);
    		btn_tinhTien.setEnabled(true);
    		
    		btn_datPhong1.setEnabled(false);
    		btn_datPhongCho.setEnabled(false);
    		btn_xemPhong.setEnabled(false);
    		btn_nhanPhongCho.setEnabled(false);
    		btn_huyPhong.setEnabled(false);
    	}else if(p.getTrangThai().equals("Phòng chờ")) {
    		btn_nhanPhongCho.setEnabled(true);
    		btn_huyPhong.setEnabled(true);
    		
    		btn_datPhong1.setEnabled(false);
    		btn_datPhongCho.setEnabled(false);
    		btn_xemPhong.setEnabled(false);
    		btn_dichVu.setEnabled(true);
    		btn_tinhTien.setEnabled(false);
    	}
    }
    //Lay ActionCommand
    public String getSelected(ButtonGroup btnGroup) {
		for(Enumeration<AbstractButton>btn = btnGroup.getElements();btn.hasMoreElements();) {
			AbstractButton button = btn.nextElement();
			if(button.isSelected()) {
				button.setSelected(false);
				return button.getActionCommand();
			}
		}
		return null;
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_datPhong1;
    private javax.swing.JButton btn_datPhongCho;
    private javax.swing.JButton btn_dichVu;
    private javax.swing.JButton btn_huyPhong;
    
    
    private JToggleButton btn_iPhong1;
    private JToggleButton btn_iPhong10;
    private JToggleButton btn_iPhong11;
    private JToggleButton btn_iPhong12;
    private JToggleButton btn_iPhong13;
    private JToggleButton btn_iPhong14;
    private JToggleButton btn_iPhong15;
    private JToggleButton btn_iPhong16;
    private JToggleButton btn_iPhong2;
    private JToggleButton btn_iPhong3;
    private JToggleButton btn_iPhong4;
    private JToggleButton btn_iPhong5;
    private JToggleButton btn_iPhong6;
    private JToggleButton btn_iPhong7;
    private JToggleButton btn_iPhong8;
    private JToggleButton btn_iPhong9;
    private javax.swing.JButton btn_lamMoi;
    private javax.swing.JButton btn_nhanPhongCho;
    private JToggleButton btn_phong1;
    private JToggleButton btn_phong10;
    private JToggleButton btn_phong11;
    private JToggleButton btn_phong12;
    private JToggleButton btn_phong13;
    private JToggleButton btn_phong14;
    private JToggleButton btn_phong15;
    private JToggleButton btn_phong16;
    private JToggleButton btn_phong2;
    private JToggleButton btn_phong3;
    private JToggleButton btn_phong4;
    private JToggleButton btn_phong5;
    private JToggleButton btn_phong6;
    private JToggleButton btn_phong7;
    private JToggleButton btn_phong8;
    private JToggleButton btn_phong9;
    private javax.swing.JButton btn_timKiem;
    private javax.swing.JButton btn_tinhTien;
    private javax.swing.JButton btn_xemPhong;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton btn_iconCho;
    private javax.swing.JButton btn_iconSD;
    private javax.swing.JButton btn_iconTrong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnl_p1;
    private javax.swing.JPanel pnl_p10;
    private javax.swing.JPanel pnl_p11;
    private javax.swing.JPanel pnl_p12;
    private javax.swing.JPanel pnl_p13;
    private javax.swing.JPanel pnl_p14;
    private javax.swing.JPanel pnl_p15;
    private javax.swing.JPanel pnl_p16;
    private javax.swing.JPanel pnl_p2;
    private javax.swing.JPanel pnl_p3;
    private javax.swing.JPanel pnl_p4;
    private javax.swing.JPanel pnl_p5;
    private javax.swing.JPanel pnl_p6;
    private javax.swing.JPanel pnl_p7;
    private javax.swing.JPanel pnl_p8;
    private javax.swing.JPanel pnl_p9;
    private javax.swing.JRadioButton rdo_dangSD;
    private javax.swing.JRadioButton rdo_phongCho;
    private javax.swing.JRadioButton rdo_phongThuong;
    private javax.swing.JRadioButton rdo_phongTrong;
    private javax.swing.JRadioButton rdo_phongVIP;
    private javax.swing.JTextPane txt_timKiem;
    


	@Override
	public void actionPerformed(ActionEvent e) {
		Object o = e.getSource();
		
		
	}

	@Override
	public void mouseClicked(MouseEvent e) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void mousePressed(MouseEvent e) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void mouseReleased(MouseEvent e) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void mouseEntered(MouseEvent e) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void mouseExited(MouseEvent e) {
		// TODO Auto-generated method stub
		
	}
    
    // End of variables declaration//GEN-END:variables
}
